question_data = [
    {"type": "boolean",
     "difficulty": "easy",
     "category": "Entertainment: Japanese Anime &amp; Manga",
     "question": "The name of the attack &quot;Kamehameha&quot; in Dragon Ball Z was named after a famous king of Hawaii.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean",
     "difficulty": "easy",
     "category": "Entertainment: Board Games",
     "question": "There is a Donald Trump Board Game, which was made in 1989.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean",
     "difficulty": "easy",
     "category": "History",
     "question": "The United States Department of Homeland Security was formed in response to the September 11th attacks.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean",
     "difficulty": "easy",
     "category": "Politics",
     "question": "Russia passed a law in 2013 which outlaws telling children that homosexuals exist.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean",
     "difficulty": "easy",
     "category": "Vehicles",
     "question": "The full English name of the car manufacturer BMW is Bavarian Motor Works",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean",
     "difficulty": "easy",
     "category": "Entertainment: Musicals &amp; Theatres",
     "question": "IMAX stands for Image Maximum.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean",
     "difficulty": "easy",
     "category": "History",
     "question": "In World War ll, Great Britain used inflatable tanks on the ports of Great Britain to divert Hitler away from Normandy D-day landing.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean",
     "difficulty": "easy",
     "category": "Entertainment: Video Games",
     "question": "Donkey Kong was originally set to be a Popeye arcade game.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean",
     "difficulty": "easy",
     "category": "Geography",
     "question": "The Republic of Malta is the smallest microstate worldwide.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean",
     "difficulty": "easy",
     "category": "Science: Computers",
     "question": "The Nvidia GTX 1080 gets its name because it can only render at a 1920x1080 screen resolution.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]}]
